lrng: fix conflicting argument types in lrng functions
This fixes compilation error to clang and gcc.

Log:
../drivers/char/lrng/lrng_interface_random_kernel.c:184:6: error: conflicting types for 'add_device_randomness'; have 'void(const void *, size_t)' {aka 'void(const void *, long unsigned int)'}
  184 | void add_device_randomness(const void *buf, size_t size)
      |      ^~~~~~~~~~~~~~~~~~~
In file included from ../arch/arm64/include/asm/pointer_auth.h:37,
                 from ../arch/arm64/include/asm/processor.h:38,
                 from ../include/linux/rcupdate.h:30,
                 from ../include/linux/rculist.h:11,
                 from ../include/linux/pid.h:5,
                 from ../include/linux/sched.h:14,
                 from ../include/linux/blkdev.h:5,
                 from ../drivers/char/lrng/lrng_interface_random_kernel.c:10:
../include/linux/random.h:15:6: note: previous declaration of 'add_device_randomness' with type 'void(const void *, unsigned int)'
   15 | void add_device_randomness(const void *buf, unsigned int len);
      |      ^~~~~~~~~~~~~~~~~
../drivers/char/lrng/lrng_interface_random_kernel.c:297:6: error: conflicting types for 'get_random_bytes'; have 'void(void *, size_t)' {aka 'void(void *, long unsigned int)'}
  297 | void get_random_bytes(void *buf, size_t nbytes)
      |      ^~~~~~~~~~~~~~
../include/linux/random.h:31:6: note: previous declaration of 'get_random_bytes' with type 'void(void *, int)'
   31 | void get_random_bytes(void *buf, int len);
      |      ^~~~~~~~~~~~~~~~

../drivers/char/lrng/lrng_interface_random_kernel.c: In function 'add_device_randomness':
../drivers/char/lrng/lrng_interface_random_kernel.c:186:41: error: 'size' undeclared (first use in this function); did you mean 'ksize'?
  186 |         lrng_pool_insert_aux((u8 *)buf, size, 0);
      |                                         ^~~~
      |                                         ksize
  CC      drivers/base/property.o

../drivers/char/lrng/lrng_interface_random_kernel.c:186:34: error: incompatible pointer to integer conversion passing 'size_t (const void *)' (aka 'unsigned long (const void *)') to parameter of type 'u32' (aka 'unsigned int') [-Wint-conversion]
  186 |         lrng_pool_insert_aux((u8 *)buf, ksize, 0);
      |                                         ^~~~~
../drivers/char/lrng/lrng_es_aux.h:14:47: note: passing argument to parameter 'inbuflen' here
   14 | int lrng_pool_insert_aux(const u8 *inbuf, u32 inbuflen, u32 entropy_bits);
      |                                               ^
1 error generated.

[Madara273]:
lrng: change ksize to len and use u64 for larger lengths
the function accepts two arguments: buf is a pointer to the buffer, and len is the size of the buffer of type unsigned int. However, in the function we use the ksize variable, which is undefined. Instead, you should use the len parameter, which is responsible for the length of the buffer.
Fix: stuck on splash.
lrng_pool_insert_aux((u8 *)buf, (u64)len, 0);

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: Id6db93f83fa69610388bb62a4b92d3f28cf80227
Co-Authored-By: Madara <156642375+Madara273@users.noreply.github.com>
Signed-off-by: RizkyMaulana58 <carlotta.montelli.0201@gmail.com>